// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0fA4OigjY6oZGUYEAdkHfbNRK492PvrI',
    appId: '1:337146578426:web:23f3425fb0ae6e09ef9043',
    messagingSenderId: '337146578426',
    projectId: 'food-delivery-4ee54',
    authDomain: 'food-delivery-4ee54.firebaseapp.com',
    storageBucket: 'food-delivery-4ee54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1pUCiDZk8FzJlE98UT0qEYVQ77ELPQUQ',
    appId: '1:337146578426:android:829801d8d5077fc0ef9043',
    messagingSenderId: '337146578426',
    projectId: 'food-delivery-4ee54',
    storageBucket: 'food-delivery-4ee54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4pQNT6MNO5WLcl-5kB6wScCbV-6cn0yc',
    appId: '1:337146578426:ios:656f0a0a64a14e5eef9043',
    messagingSenderId: '337146578426',
    projectId: 'food-delivery-4ee54',
    storageBucket: 'food-delivery-4ee54.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4pQNT6MNO5WLcl-5kB6wScCbV-6cn0yc',
    appId: '1:337146578426:ios:656f0a0a64a14e5eef9043',
    messagingSenderId: '337146578426',
    projectId: 'food-delivery-4ee54',
    storageBucket: 'food-delivery-4ee54.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0fA4OigjY6oZGUYEAdkHfbNRK492PvrI',
    appId: '1:337146578426:web:8c2e5b7dc5f82d9aef9043',
    messagingSenderId: '337146578426',
    projectId: 'food-delivery-4ee54',
    authDomain: 'food-delivery-4ee54.firebaseapp.com',
    storageBucket: 'food-delivery-4ee54.appspot.com',
  );

}